version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["./wait-for-db.sh", "db", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--reload"]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=code_index
      - POSTGRES_USER=optiq
      - POSTGRES_PASSWORD=secure_password
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-your-key}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./backend
    command: ["./wait-for-db.sh", "db", "python", "celery_worker.py"]
    volumes:
      - ./backend:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=code_index
      - POSTGRES_USER=optiq
      - POSTGRES_PASSWORD=secure_password
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-your-key}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    user: "1000:1000"
    depends_on:
      - db
      - redis
      - backend

  db:
    build: ./db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=optiq
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=code_index
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U optiq -d code_index"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
